version: '2'
services:
  server:
    environment:
      - 'PGHOST=postgres'
      - 'PGPORT=5432'
      - 'PORT=3000'
      - 'NODE_ENV=production'
    # pulls the image tictactoe from aevartg to compose with another image
    image: 'aevartg/tictactoe:${GIT_COMMIT}'
    ports:
      - '80:3000'
      - '8080:8080'
    depends_on:
      - 'postgres'
  postgres:
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=mysecretpassword'
    # second image for use with tictactoe for the database
    image: postgres
    ports:
      - "5432:5432"
